// tslint:disable
/**
 * Cakemix Server API
 * Definition of Cakemix Server API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@wonder-wonder.xyz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";
